version: '3.8'

services:

  postgres:
    container_name: postgres_container_new
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    expose:
      - 5432

  pgadmin:
    container_name: pgadmin_container_new

    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

    networks:
      - app-network
    restart: unless-stopped
  
  core:
    build:
      context: ../services/core-service
      dockerfile: Dockerfile
    container_name: core_service
    environment:
      - DATABASE_DIALECT=postgresql+psycopg2
      - DATABASE_HOSTNAME=postgres_container_new
      - DATABASE_NAME=CORE-DB
      - DATABASE_NAME_USER=IAM-DB
      - DATABASE_PASSWORD=admin
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DEBUG_MODE=False
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.core-service.rule=Host(`core.localhost`)"
      - "traefik.http.routers.core-service.entrypoints=web"
      - "traefik.http.services.core-service.loadbalancer.server.port=80"
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
