FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app /app/fastAPI

WORKDIR /app/fastAPI


CMD ["uvicorn", "App.main:app", "--host", "0.0.0.0", "--port", "80","--reload"]

